// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CCSwitchInstalled() {
  return window['go']['main']['App']['CCSwitchInstalled']();
}

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function ListApps() {
  return window['go']['main']['App']['ListApps']();
}

export function OpenCCSwitch() {
  return window['go']['main']['App']['OpenCCSwitch']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetApp(arg1) {
  return window['go']['main']['App']['SetApp'](arg1);
}

export function SetBarWidth(arg1) {
  return window['go']['main']['App']['SetBarWidth'](arg1);
}

export function SetCardHeight(arg1) {
  return window['go']['main']['App']['SetCardHeight'](arg1);
}

export function SetCollapsed(arg1) {
  return window['go']['main']['App']['SetCollapsed'](arg1);
}

export function SetUserHeight(arg1) {
  return window['go']['main']['App']['SetUserHeight'](arg1);
}

export function ToggleShow() {
  return window['go']['main']['App']['ToggleShow']();
}
