// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {snapshot} from '../models';

export function CCSwitchInstalled():Promise<boolean>;

export function GetSnapshot():Promise<snapshot.Snapshot>;

export function ListApps():Promise<Array<string>>;

export function OpenCCSwitch():Promise<void>;

export function Quit():Promise<void>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetApp(arg1:string):Promise<void>;

export function SetBarWidth(arg1:number):Promise<void>;

export function SetCardHeight(arg1:number):Promise<void>;

export function SetCollapsed(arg1:boolean):Promise<void>;

export function SetUserHeight(arg1:number):Promise<void>;

export function ToggleShow():Promise<void>;
